services:
  - type: web
    name: dsdash
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python -V
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "python manage.py migrate --noinput && gunicorn dsdash.wsgi:application --preload --workers=2 --timeout=120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: dsdash-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9

databases:
  - name: dsdash-db
    plan: free

